version: '3.8'

services:
  web:
    build:
      context: api/
      dockerfile: build/Dockerfile
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1] web

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - web
