version: '3.8'

services:
  web:
    build:
      context: api/
      dockerfile: build/Dockerfile
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
