version: '3.8'

services:
  web:
    build:
      context: api/
      dockerfile: build/Dockerfile
    working_dir: /app/backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --reload --timeout 3600 --max-requests 1 --workers 4
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - ANTHROPIC_API_KEY=""
    depends_on:
      - redis

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - web

  mcp:
    build:
      context: mcp/
      dockerfile: build/Dockerfile
    command: python server.py
    ports:
      - "5000:5000"
    volumes:
      - ./mcp:/app
    depends_on:
      - web

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: